[project]
name = "earth2studio-aifs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "cartopy>=0.25.0",
    "earth2studio[aifs2ens,data]",
    "matplotlib>=3.11.0",
    "torch<2.13",
    "triton>=3.7.1",
]

[tool.uv.sources]
earth2studio = { git = "https://github.com/ahijevyc/earth2studio.git", branch = "ahijevyc/aifs2ens" }
torch = { index = "pytorch-cu121" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.extra-build-dependencies]
flash-attn = ["torch", "packaging"]
